let keyArray = [
  "accentColor",
  "additiveSymbols",
  "alignContent",
  "alignItems",
  "alignSelf",
  "alignmentBaseline",
  "all",
  "animation",
  "animationComposition",
  "animationDelay",
  "animationDirection",
  "animationDuration",
  "animationFillMode",
  "animationIterationCount",
  "animationName",
  "animationPlayState",
  "animationRange",
  "animationRangeEnd",
  "animationRangeStart",
  "animationTimeline",
  "animationTimingFunction",
  "appRegion",
  "appearance",
  "ascentOverride",
  "aspectRatio",
  "backdropFilter",
  "backfaceVisibility",
  "background",
  "backgroundAttachment",
  "backgroundBlendMode",
  "backgroundClip",
  "backgroundColor",
  "backgroundImage",
  "backgroundOrigin",
  "backgroundPosition",
  "backgroundPositionX",
  "backgroundPositionY",
  "backgroundRepeat",
  "backgroundSize",
  "basePalette",
  "baselineShift",
  "baselineSource",
  "blockSize",
  "border",
  "borderBlock",
  "borderBlockColor",
  "borderBlockEnd",
  "borderBlockEndColor",
  "borderBlockEndStyle",
  "borderBlockEndWidth",
  "borderBlockStart",
  "borderBlockStartColor",
  "borderBlockStartStyle",
  "borderBlockStartWidth",
  "borderBlockStyle",
  "borderBlockWidth",
  "borderBottom",
  "borderBottomColor",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStyle",
  "borderBottomWidth",
  "borderCollapse",
  "borderColor",
  "borderEndEndRadius",
  "borderEndStartRadius",
  "borderImage",
  "borderImageOutset",
  "borderImageRepeat",
  "borderImageSlice",
  "borderImageSource",
  "borderImageWidth",
  "borderInline",
  "borderInlineColor",
  "borderInlineEnd",
  "borderInlineEndColor",
  "borderInlineEndStyle",
  "borderInlineEndWidth",
  "borderInlineStart",
  "borderInlineStartColor",
  "borderInlineStartStyle",
  "borderInlineStartWidth",
  "borderInlineStyle",
  "borderInlineWidth",
  "borderLeft",
  "borderLeftColor",
  "borderLeftStyle",
  "borderLeftWidth",
  "borderRadius",
  "borderRight",
  "borderRightColor",
  "borderRightStyle",
  "borderRightWidth",
  "borderSpacing",
  "borderStartEndRadius",
  "borderStartStartRadius",
  "borderStyle",
  "borderTop",
  "borderTopColor",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStyle",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "boxShadow",
  "boxSizing",
  "breakAfter",
  "breakBefore",
  "breakInside",
  "bufferedRendering",
  "captionSide",
  "caretColor",
  "clear",
  "clip",
  "clipPath",
  "clipRule",
  "color",
  "color red",
  "colorInterpolation",
  "colorInterpolationFilters",
  "colorRendering",
  "colorScheme",
  "columnCount",
  "columnFill",
  "columnGap",
  "columnRule",
  "columnRuleColor",
  "columnRuleStyle",
  "columnRuleWidth",
  "columnSpan",
  "columnWidth",
  "columns",
  "contain",
  "containIntrinsicBlockSize",
  "containIntrinsicHeight",
  "containIntrinsicInlineSize",
  "containIntrinsicSize",
  "containIntrinsicWidth",
  "container",
  "containerName",
  "containerType",
  "content",
  "contentVisibility",
  "counterIncrement",
  "counterReset",
  "counterSet",
  "cursor",
  "cx",
  "cy",
  "d",
  "descentOverride",
  "direction",
  "display",
  "dominantBaseline",
  "emptyCells",
  "fallback",
  "fill",
  "fillOpacity",
  "fillRule",
  "filter",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexFlow",
  "flexGrow",
  "flexShrink",
  "flexWrap",
  "float",
  "floodColor",
  "floodOpacity",
  "font",
  "fontDisplay",
  "fontFamily",
  "fontFeatureSettings",
  "fontKerning",
  "fontOpticalSizing",
  "fontPalette",
  "fontSize",
  "fontStretch",
  "fontStyle",
  "fontSynthesis",
  "fontSynthesisSmallCaps",
  "fontSynthesisStyle",
  "fontSynthesisWeight",
  "fontVariant",
  "fontVariantAlternates",
  "fontVariantCaps",
  "fontVariantEastAsian",
  "fontVariantLigatures",
  "fontVariantNumeric",
  "fontVariantPosition",
  "fontVariationSettings",
  "fontWeight",
  "forcedColorAdjust",
  "gap",
  "grid",
  "gridArea",
  "gridAutoColumns",
  "gridAutoFlow",
  "gridAutoRows",
  "gridColumn",
  "gridColumnEnd",
  "gridColumnGap",
  "gridColumnStart",
  "gridGap",
  "gridRow",
  "gridRowEnd",
  "gridRowGap",
  "gridRowStart",
  "gridTemplate",
  "gridTemplateAreas",
  "gridTemplateColumns",
  "gridTemplateRows",
  "height",
  "hyphenateCharacter",
  "hyphenateLimitChars",
  "hyphens",
  "imageOrientation",
  "imageRendering",
  "inherits",
  "initialLetter",
  "initialValue",
  "inlineSize",
  "inset",
  "insetBlock",
  "insetBlockEnd",
  "insetBlockStart",
  "insetInline",
  "insetInlineEnd",
  "insetInlineStart",
  "isolation",
  "justifyContent",
  "justifyItems",
  "justifySelf",
  "left",
  "letterSpacing",
  "lightingColor",
  "lineBreak",
  "lineGapOverride",
  "lineHeight",
  "listStyle",
  "listStyleImage",
  "listStylePosition",
  "listStyleType",
  "margin",
  "marginBlock",
  "marginBlockEnd",
  "marginBlockStart",
  "marginBottom",
  "marginInline",
  "marginInlineEnd",
  "marginInlineStart",
  "marginLeft",
  "marginRight",
  "marginTop",
  "marker",
  "markerEnd",
  "markerMid",
  "markerStart",
  "mask",
  "maskClip",
  "maskComposite",
  "maskImage",
  "maskMode",
  "maskOrigin",
  "maskPosition",
  "maskRepeat",
  "maskSize",
  "maskType",
  "mathDepth",
  "mathShift",
  "mathStyle",
  "maxBlockSize",
  "maxHeight",
  "maxInlineSize",
  "maxWidth",
  "minBlockSize",
  "minHeight",
  "minInlineSize",
  "minWidth",
  "mixBlendMode",
  "negative",
  "objectFit",
  "objectPosition",
  "objectViewBox",
  "offset",
  "offsetAnchor",
  "offsetDistance",
  "offsetPath",
  "offsetPosition",
  "offsetRotate",
  "opacity",
  "order",
  "orphans",
  "outline",
  "outlineColor",
  "outlineOffset",
  "outlineStyle",
  "outlineWidth",
  "overflow",
  "overflowAnchor",
  "overflowClipMargin",
  "overflowWrap",
  "overflowX",
  "overflowY",
  "overlay",
  "overrideColors",
  "overscrollBehavior",
  "overscrollBehaviorBlock",
  "overscrollBehaviorInline",
  "overscrollBehaviorX",
  "overscrollBehaviorY",
  "pad",
  "padding",
  "paddingBlock",
  "paddingBlockEnd",
  "paddingBlockStart",
  "paddingBottom",
  "paddingInline",
  "paddingInlineEnd",
  "paddingInlineStart",
  "paddingLeft",
  "paddingRight",
  "paddingTop",
  "page",
  "pageBreakAfter",
  "pageBreakBefore",
  "pageBreakInside",
  "pageOrientation",
  "paintOrder",
  "perspective",
  "perspectiveOrigin",
  "placeContent",
  "placeItems",
  "placeSelf",
  "pointerEvents",
  "position",
  "prefix",
  "quotes",
  "r",
  "range",
  "resize",
  "right",
  "rotate",
  "rowGap",
  "rubyPosition",
  "rx",
  "ry",
  "scale",
  "scrollBehavior",
  "scrollMargin",
  "scrollMarginBlock",
  "scrollMarginBlockEnd",
  "scrollMarginBlockStart",
  "scrollMarginBottom",
  "scrollMarginInline",
  "scrollMarginInlineEnd",
  "scrollMarginInlineStart",
  "scrollMarginLeft",
  "scrollMarginRight",
  "scrollMarginTop",
  "scrollPadding",
  "scrollPaddingBlock",
  "scrollPaddingBlockEnd",
  "scrollPaddingBlockStart",
  "scrollPaddingBottom",
  "scrollPaddingInline",
  "scrollPaddingInlineEnd",
  "scrollPaddingInlineStart",
  "scrollPaddingLeft",
  "scrollPaddingRight",
  "scrollPaddingTop",
  "scrollSnapAlign",
  "scrollSnapStop",
  "scrollSnapType",
  "scrollTimeline",
  "scrollTimelineAxis",
  "scrollTimelineName",
  "scrollbarColor",
  "scrollbarGutter",
  "scrollbarWidth",
  "shapeImageThreshold",
  "shapeMargin",
  "shapeOutside",
  "shapeRendering",
  "size",
  "sizeAdjust",
  "speak",
  "speakAs",
  "src",
  "stopColor",
  "stopOpacity",
  "stroke",
  "strokeDasharray",
  "strokeDashoffset",
  "strokeLinecap",
  "strokeLinejoin",
  "strokeMiterlimit",
  "strokeOpacity",
  "strokeWidth",
  "suffix",
  "symbols",
  "syntax",
  "system",
  "tabSize",
  "tableLayout",
  "textAlign",
  "textAlignLast",
  "textAnchor",
  "textCombineUpright",
  "textDecoration",
  "textDecorationColor",
  "textDecorationLine",
  "textDecorationSkipInk",
  "textDecorationStyle",
  "textDecorationThickness",
  "textEmphasis",
  "textEmphasisColor",
  "textEmphasisPosition",
  "textEmphasisStyle",
  "textIndent",
  "textOrientation",
  "textOverflow",
  "textRendering",
  "textShadow",
  "textSizeAdjust",
  "textTransform",
  "textUnderlineOffset",
  "textUnderlinePosition",
  "textWrap",
  "timelineScope",
  "top",
  "touchAction",
  "transform",
  "transformBox",
  "transformOrigin",
  "transformStyle",
  "transition",
  "transitionBehavior",
  "transitionDelay",
  "transitionDuration",
  "transitionProperty",
  "transitionTimingFunction",
  "translate",
  "unicodeBidi",
  "unicodeRange",
  "userSelect",
  "vectorEffect",
  "verticalAlign",
  "viewTimeline",
  "viewTimelineAxis",
  "viewTimelineInset",
  "viewTimelineName",
  "viewTransitionName",
  "visibility",
  "webkitAlignContent",
  "webkitAlignItems",
  "webkitAlignSelf",
  "webkitAnimation",
  "webkitAnimationDelay",
  "webkitAnimationDirection",
  "webkitAnimationDuration",
  "webkitAnimationFillMode",
  "webkitAnimationIterationCount",
  "webkitAnimationName",
  "webkitAnimationPlayState",
  "webkitAnimationTimingFunction",
  "webkitAppRegion",
  "webkitAppearance",
  "webkitBackfaceVisibility",
  "webkitBackgroundClip",
  "webkitBackgroundOrigin",
  "webkitBackgroundSize",
  "webkitBorderAfter",
  "webkitBorderAfterColor",
  "webkitBorderAfterStyle",
  "webkitBorderAfterWidth",
  "webkitBorderBefore",
  "webkitBorderBeforeColor",
  "webkitBorderBeforeStyle",
  "webkitBorderBeforeWidth",
  "webkitBorderBottomLeftRadius",
  "webkitBorderBottomRightRadius",
  "webkitBorderEnd",
  "webkitBorderEndColor",
  "webkitBorderEndStyle",
  "webkitBorderEndWidth",
  "webkitBorderHorizontalSpacing",
  "webkitBorderImage",
  "webkitBorderRadius",
  "webkitBorderStart",
  "webkitBorderStartColor",
  "webkitBorderStartStyle",
  "webkitBorderStartWidth",
  "webkitBorderTopLeftRadius",
  "webkitBorderTopRightRadius",
  "webkitBorderVerticalSpacing",
  "webkitBoxAlign",
  "webkitBoxDecorationBreak",
  "webkitBoxDirection",
  "webkitBoxFlex",
  "webkitBoxOrdinalGroup",
  "webkitBoxOrient",
  "webkitBoxPack",
  "webkitBoxReflect",
  "webkitBoxShadow",
  "webkitBoxSizing",
  "webkitClipPath",
  "webkitColumnBreakAfter",
  "webkitColumnBreakBefore",
  "webkitColumnBreakInside",
  "webkitColumnCount",
  "webkitColumnGap",
  "webkitColumnRule",
  "webkitColumnRuleColor",
  "webkitColumnRuleStyle",
  "webkitColumnRuleWidth",
  "webkitColumnSpan",
  "webkitColumnWidth",
  "webkitColumns",
  "webkitFilter",
  "webkitFlex",
  "webkitFlexBasis",
  "webkitFlexDirection",
  "webkitFlexFlow",
  "webkitFlexGrow",
  "webkitFlexShrink",
  "webkitFlexWrap",
  "webkitFontFeatureSettings",
  "webkitFontSmoothing",
  "webkitHyphenateCharacter",
  "webkitJustifyContent",
  "webkitLineBreak",
  "webkitLineClamp",
  "webkitLocale",
  "webkitLogicalHeight",
  "webkitLogicalWidth",
  "webkitMarginAfter",
  "webkitMarginBefore",
  "webkitMarginEnd",
  "webkitMarginStart",
  "webkitMask",
  "webkitMaskBoxImage",
  "webkitMaskBoxImageOutset",
  "webkitMaskBoxImageRepeat",
  "webkitMaskBoxImageSlice",
  "webkitMaskBoxImageSource",
  "webkitMaskBoxImageWidth",
  "webkitMaskClip",
  "webkitMaskComposite",
  "webkitMaskImage",
  "webkitMaskOrigin",
  "webkitMaskPosition",
  "webkitMaskPositionX",
  "webkitMaskPositionY",
  "webkitMaskRepeat",
  "webkitMaskSize",
  "webkitMaxLogicalHeight",
  "webkitMaxLogicalWidth",
  "webkitMinLogicalHeight",
  "webkitMinLogicalWidth",
  "webkitOpacity",
  "webkitOrder",
  "webkitPaddingAfter",
  "webkitPaddingBefore",
  "webkitPaddingEnd",
  "webkitPaddingStart",
  "webkitPerspective",
  "webkitPerspectiveOrigin",
  "webkitPerspectiveOriginX",
  "webkitPerspectiveOriginY",
  "webkitPrintColorAdjust",
  "webkitRtlOrdering",
  "webkitRubyPosition",
  "webkitShapeImageThreshold",
  "webkitShapeMargin",
  "webkitShapeOutside",
  "webkitTapHighlightColor",
  "webkitTextCombine",
  "webkitTextDecorationsInEffect",
  "webkitTextEmphasis",
  "webkitTextEmphasisColor",
  "webkitTextEmphasisPosition",
  "webkitTextEmphasisStyle",
  "webkitTextFillColor",
  "webkitTextOrientation",
  "webkitTextSecurity",
  "webkitTextSizeAdjust",
  "webkitTextStroke",
  "webkitTextStrokeColor",
  "webkitTextStrokeWidth",
  "webkitTransform",
  "webkitTransformOrigin",
  "webkitTransformOriginX",
  "webkitTransformOriginY",
  "webkitTransformOriginZ",
  "webkitTransformStyle",
  "webkitTransition",
  "webkitTransitionDelay",
  "webkitTransitionDuration",
  "webkitTransitionProperty",
  "webkitTransitionTimingFunction",
  "webkitUserDrag",
  "webkitUserModify",
  "webkitUserSelect",
  "webkitWritingMode",
  "whiteSpace",
  "whiteSpaceCollapse",
  "widows",
  "width",
  "willChange",
  "wordBreak",
  "wordSpacing",
  "wordWrap",
  "writingMode",
  "x",
  "y",
  "zIndex",
  "zoom",
  "cssText",
  "length",
  "parentRule",
  "cssFloat",
];

const cssValues = {
  accentColor: ["<color>"],
  additiveSymbols: ["<string>"],
  alignContent: [
    "stretch",
    "center",
    "flex-start",
    "flex-end",
    "space-between",
    "space-around",
    "space-evenly",
    "start",
    "end",
    "left",
    "right",
    "baseline",
    "first baseline",
    "last baseline",
    "safe center",
    "unsafe center",
  ],
  alignItems: [
    "stretch",
    "center",
    "flex-start",
    "flex-end",
    "baseline",
    "first baseline",
    "last baseline",
    "start",
    "end",
    "self-start",
    "self-end",
    "safe center",
    "unsafe center",
  ],
  alignSelf: [
    "auto",
    "stretch",
    "center",
    "flex-start",
    "flex-end",
    "baseline",
    "first baseline",
    "last baseline",
    "start",
    "end",
    "self-start",
    "self-end",
    "safe center",
    "unsafe center",
  ],
  alignmentBaseline: [
    "auto",
    "baseline",
    "before-edge",
    "text-before-edge",
    "middle",
    "central",
    "after-edge",
    "text-after-edge",
    "ideographic",
    "alphabetic",
    "hanging",
    "mathematical",
    "inherit",
  ],
  all: ["initial", "inherit", "unset"],
  animation: [
    "<animation-name> || <animation-duration> || <animation-timing-function> || <animation-delay> || <animation-iteration-count> || <animation-direction> || <animation-fill-mode> || <animation-play-state> || <animation-composition>",
  ],
  animationComposition: ["none", "keyframes", "steps"],
  animationDelay: ["<time>", "infinite"],
  animationDirection: [
    "normal",
    "reverse",
    "alternate",
    "alternate-reverse",
    "inherit",
  ],
  animationDuration: ["<time>", "infinite"],
  animationFillMode: ["none", "forwards", "backwards", "both", "inherit"],
  animationIterationCount: ["<number>", "infinite"],
  animationName: ["<keyframes-name>", "none", "inherit"],
  animationPlayState: ["running", "paused", "inherit"],
  animationRange: ["<range-name>"],
  animationRangeEnd: ["<range-name>", "none"],
  animationRangeStart: ["<range-name>", "none"],
  animationTimeline: ["<animation-timeline-name>"],
  animationTimingFunction: ["<timing-function>"],
  appRegion: ["drag", "drag-no-background", "no-drag"],
  appearance: [
    "auto",
    "none",
    "button",
    "button-bevel",
    "caps-lock-indicator",
    "caret",
    "checkbox",
    "default-button",
    "listbox",
    "listitem",
    "media-fullscreen-button",
    "media-mute-button",
    "media-play-button",
    "media-seek-back-button",
    "media-seek-forward-button",
    "media-slider",
    "media-sliderthumb",
    "menulist",
    "menulist-button",
    "menulist-text",
    "menulist-textfield",
    "meter",
    "none",
    "push-button",
    "radio",
    "searchfield",
    "searchfield-cancel-button",
    "searchfield-decoration",
    "searchfield-results-button",
    "searchfield-results-decoration",
    "slider-horizontal",
    "slider-vertical",
    "sliderthumb-horizontal",
    "sliderthumb-vertical",
    "square-button",
    "textarea",
    "textfield",
    "none",
  ],
  ascentOverride: ["<integer>"],
  aspectRatio: ["auto", "<ratio>"],
  backdropFilter: ["none", "<filter-function-list>"],
  backfaceVisibility: ["visible", "hidden"],
  background: ["<bg-layer>", "<final-bg-layer>"],
  backgroundAttachment: ["scroll", "fixed", "local", "inherit"],
  backgroundBlendMode: [
    "normal",
    "multiply",
    "screen",
    "overlay",
    "darken",
    "lighten",
    "color-dodge",
    "color-burn",
    "hard-light",
    "soft-light",
    "difference",
    "exclusion",
    "hue",
    "saturation",
    "color",
    "luminosity",
    "inherit",
  ],
  backgroundClip: [
    "border-box",
    "padding-box",
    "content-box",
    "text",
    "no-clip",
  ],
  backgroundColor: ["<color>", "transparent", "currentColor", "inherit"],
  backgroundImage: ["none", "<bg-image>"],
  backgroundOrigin: ["padding-box", "border-box", "content-box", "inherit"],
  backgroundPosition: [
    "<length-percentage>",
    "left",
    "center",
    "right",
    "top",
    "bottom",
    "inherit",
  ],
  backgroundPositionX: [
    "<length-percentage>",
    "left",
    "center",
    "right",
    "inherit",
  ],
  backgroundPositionY: [
    "<length-percentage>",
    "top",
    "center",
    "bottom",
    "inherit",
  ],
  backgroundRepeat: [
    "repeat",
    "repeat-x",
    "repeat-y",
    "no-repeat",
    "space",
    "round",
    "inherit",
  ],
  backgroundSize: ["<bg-size>", "cover", "contain"],
  basePalette: ["<name>"],
  baselineShift: ["<length-percentage>", "sub", "super"],
  baselineSource: ["font", "first", "author", "auto"],
  blockSize: [
    "<length-percentage>",
    "auto",
    "min-content",
    "max-content",
    "fit-content",
    "inherit",
  ],
  border: ["<line-width>", "<line-style>", "<color>"],
  borderBlock: ["<line-width>", "<line-style>", "<color>"],
  borderBlockColor: ["<color>"],
  borderBlockEnd: ["<line-width>", "<line-style>", "<color>"],
  borderBlockEndColor: ["<color>"],
  borderBlockEndStyle: ["<line-style>"],
  borderBlockEndWidth: ["<line-width>"],
  borderBlockStart: ["<line-width>", "<line-style>", "<color>"],
  borderBlockStartColor: ["<color>"],
  borderBlockStartStyle: ["<line-style>"],
  borderBlockStartWidth: ["<line-width>"],
  borderBlockStyle: ["<line-style>"],
  borderBlockWidth: ["<line-width>"],
  borderBottom: ["<line-width>", "<line-style>", "<color>"],
  borderBottomColor: ["<color>"],
  borderBottomLeftRadius: ["<length-percentage>", "auto"],
  borderBottomRightRadius: ["<length-percentage>", "auto"],
  borderBottomStyle: ["<line-style>"],
  borderBottomWidth: ["<line-width>"],
  borderCollapse: ["collapse", "separate", "inherit"],
  borderColor: ["<color>", "transparent", "currentColor", "inherit"],
  borderEndEndRadius: ["<length-percentage>", "auto"],
  borderEndStartRadius: ["<length-percentage>", "auto"],
  borderImage: [
    "none",
    "<image>",
    "<number>",
    "<slice>",
    "<width>",
    "<outset>",
    "<repeat>",
  ],
  borderImageOutset: ["<length>", "<number>"],
  borderImageRepeat: ["stretch", "repeat", "round", "space"],
  borderImageSlice: ["<number>", "<percentage>", "fill", "auto"],
  borderImageSource: ["none", "<image>"],
  borderImageWidth: ["<length>", "<percentage>", "<number>", "auto"],
  borderInline: ["<line-width>", "<line-style>", "<color>"],
  borderInlineColor: ["<color>"],
  borderInlineEnd: ["<line-width>", "<line-style>", "<color>"],
  borderInlineEndColor: ["<color>"],
  borderInlineEndStyle: ["<line-style>"],
  borderInlineEndWidth: ["<line-width>"],
  borderInlineStart: ["<line-width>", "<line-style>", "<color>"],
  borderInlineStartColor: ["<color>"],
  borderInlineStartStyle: ["<line-style>"],
  borderInlineStartWidth: ["<line-width>"],
  borderInlineStyle: ["<line-style>"],
  borderInlineWidth: ["<line-width>"],
  borderLeft: ["<line-width>", "<line-style>", "<color>"],
  borderLeftColor: ["<color>"],
  borderLeftStyle: ["<line-style>"],
  borderLeftWidth: ["<line-width>"],
  borderRadius: ["<length-percentage>", "auto"],
  borderRight: ["<line-width>", "<line-style>", "<color>"],
  borderRightColor: ["<color>"],
  borderRightStyle: ["<line-style>"],
  borderRightWidth: ["<line-width>"],
  borderSpacing: ["<length-percentage>", "inherit"],
  borderStartEndRadius: ["<length-percentage>", "auto"],
  borderStartStartRadius: ["<length-percentage>", "auto"],
  borderStyle: ["<line-style>"],
  borderTop: ["<line-width>", "<line-style>", "<color>"],
  borderTopColor: ["<color>"],
  borderTopLeftRadius: ["<length-percentage>", "auto"],
  borderTopRightRadius: ["<length-percentage>", "auto"],
  borderTopStyle: ["<line-style>"],
  borderTopWidth: ["<line-width>"],
  borderWidth: ["<line-width>", "thin", "medium", "thick"],
  bottom: ["<length-percentage>", "auto", "inherit"],
  boxShadow: ["none", "<shadow>", "inherit"],
  boxSizing: ["content-box", "border-box"],
  breakAfter: [
    "auto",
    "avoid",
    "avoid-page",
    "page",
    "left",
    "right",
    "recto",
    "verso",
    "avoid-column",
    "avoid-region",
    "column",
    "region",
  ],
  breakBefore: [
    "auto",
    "avoid",
    "avoid-page",
    "page",
    "left",
    "right",
    "recto",
    "verso",
    "avoid-column",
    "avoid-region",
    "column",
    "region",
  ],
  breakInside: ["auto", "avoid", "avoid-page", "avoid-column", "avoid-region"],
  bufferedRendering: ["auto", "dynamic", "static"],
  captionSide: [
    "top",
    "bottom",
    "block-start",
    "block-end",
    "inline-start",
    "inline-end",
  ],
  caretColor: ["<color>", "auto"],
  clear: ["none", "left", "right", "both"],
  clip: ["<shape>"],
  clipPath: ["none", "<clip-source>", "inherit"],
  clipRule: ["nonzero", "evenodd"],
  color: ["<color>", "transparent", "currentColor"],
  colorInterpolation: ["auto", "srgb", "linearRGB"],
  colorInterpolationFilters: ["auto", "srgb", "linearRGB"],
  colorRendering: ["auto", "optimizeSpeed", "optimizeQuality"],
  colorScheme: ["auto", "dark", "light", "<custom-ident>"],
  columnCount: ["auto", "<integer>"],
  columnFill: ["auto", "balance", "auto-fill", "auto-fit"],
  columnGap: ["normal", "<length-percentage>"],
  columnRule: ["<line-width>", "<line-style>", "<color>"],
  columnRuleColor: ["<color>"],
  columnRuleStyle: ["<line-style>"],
  columnRuleWidth: ["<line-width>"],
  columnSpan: ["none", "all"],
  columnWidth: ["auto", "<length-percentage>"],
  columns: ["<length-percentage>", "auto"],
  contain: ["none", "strict", "content", "size", "layout", "style", "paint"],
  containIntrinsicBlockSize: ["none", "auto", "<length-percentage>"],
  containIntrinsicHeight: ["none", "auto", "<length-percentage>"],
  containIntrinsicInlineSize: ["none", "auto", "<length-percentage>"],
  containIntrinsicSize: ["none", "auto", "<length-percentage>"],
  containIntrinsicWidth: ["none", "auto", "<length-percentage>"],
  container: ["none", "auto"],
  containerName: ["<string>"],
  containerType: ["<custom-ident>"],
  content: [
    "normal",
    "none",
    "contents",
    "<string>",
    "<url>",
    "<counter>",
    "<attr>",
    "<open-quote>",
    "<close-quote>",
    "<no-open-quote>",
    "<no-close-quote>",
  ],
  contentVisibility: ["visible", "hidden", "collapse"],
  counterIncrement: ["none", "<custom-ident>", "<integer>", "inherit"],
  counterReset: ["none", "<custom-ident>", "<integer>", "inherit"],
  counterSet: ["none", "<custom-ident>", "<integer>", "inherit"],
  cursor: [
    "<url>",
    "auto",
    "default",
    "none",
    "context-menu",
    "help",
    "pointer",
    "progress",
    "wait",
    "cell",
    "crosshair",
    "text",
    "vertical-text",
    "alias",
    "copy",
    "move",
    "no-drop",
    "not-allowed",
    "grab",
    "grabbing",
    "all-scroll",
    "col-resize",
    "row-resize",
    "n-resize",
    "e-resize",
    "s-resize",
    "w-resize",
    "ne-resize",
    "nw-resize",
    "se-resize",
    "sw-resize",
    "ew-resize",
    "ns-resize",
    "nesw-resize",
    "nwse-resize",
    "zoom-in",
    "zoom-out",
    "grab",
    "grabbing",
  ],
  cx: ["<length-percentage>", "auto"],
  cy: ["<length-percentage>", "auto"],
  d: ["<shape>"],
  descentOverride: ["auto", "<percentage>"],
  direction: ["ltr", "rtl"],
  display: [
    "block",
    "inline",
    "run-in",
    "flow",
    "flow-root",
    "table",
    "flex",
    "grid",
    "ruby",
    "subgrid",
    "block flow",
    "inline table",
    "flex run-in",
    "list-item",
    "list-item block",
    "list-item inline",
    "list-item flow",
    "list-item flow-root",
    "flow list-item block",
    "table-row-group",
    "table-header-group",
    "table-footer-group",
    "table-row",
    "table-cell",
    "table-column-group",
    "table-column",
    "table-caption",
    "ruby-base",
    "ruby-text",
    "ruby-base-container",
    "ruby-text-container",
    "contents",
    "none",
    "inline-block",
    "inline-table",
    "inline-flex",
    "inline-grid",
    "inline flow",
    "inline flow-root",
    "flow list-item",
    "flow-root",
    "table-row group",
    "table header-group",
    "table footer-group",
    "table row",
    "table cell",
    "ruby base",
    "ruby text",
    "ruby base-container",
    "ruby text-container",
    "table-row-group flow",
    "table-header-group flow",
    "table-footer-group flow",
    "table-row flow",
    "table-cell flow",
    "table-column-group flow",
    "table-column flow",
    "table-caption flow",
    "ruby-base flow",
    "ruby-text flow",
    "ruby-base-container flow",
    "ruby-text-container flow",
    "run-in flow",
    "block ruby",
    "inline ruby",
    "flow list-item ruby",
    "table ruby",
    "flex ruby",
    "grid ruby",
    "run-in ruby",
    "block flow ruby",
    "inline table ruby",
    "flex run-in ruby",
    "list-item ruby",
    "flow-root ruby",
    "flow list-item ruby",
    "table-row group ruby",
    "table-header-group ruby",
    "table-footer-group ruby",
    "table-row ruby",
    "table-cell ruby",
    "table-column-group ruby",
    "table-column ruby",
    "table-caption ruby",
    "ruby-base ruby",
    "ruby-text ruby",
    "ruby-base-container ruby",
    "ruby-text-container ruby",
    "contents ruby",
    "inline-block ruby",
    "inline-table ruby",
    "inline-flex ruby",
    "inline-grid ruby",
    "none ruby",
  ],
  dominantBaseline: [
    "auto",
    "use-script",
    "no-change",
    "reset-size",
    "ideographic",
    "alphabetic",
    "hanging",
    "mathematical",
    "central",
    "middle",
    "text-before-edge",
    "text-after-edge",
    "text-top",
    "text-bottom",
  ],
  emptyCells: ["show", "hide"],
  fallback: ["<string>"],
  fill: ["<paint>", "<color>", "currentcolor"],
  fillOpacity: ["<number>", "inherit"],
  fillRule: ["nonzero", "evenodd"],
  filter: ["<url>", "none", "inherit"],
  flex: ["none", "<flex-grow>", "<flex-shrink>", "<flex-basis>"],
  flexBasis: ["auto", "content", "<width>"],
  flexDirection: ["row", "row-reverse", "column", "column-reverse"],
  flexFlow: ["<flex-direction>", "<flex-wrap>"],
  flexGrow: ["<number>"],
  flexShrink: ["<number>"],
  flexWrap: ["nowrap", "wrap", "wrap-reverse"],
  float: ["left", "right", "none", "inline-start", "inline-end"],
  floodColor: ["<color>"],
  floodOpacity: ["<number>", "inherit"],
  font: [
    " <font-style> , <font-variant-css21> , <font-weight> , <font-size> , <line-height> , <font-family> ]",
    "caption",
    "icon",
    "menu",
    "message-box",
    "small-caption",
    "status-bar",
  ],
  fontDisplay: ["auto", "block", "swap", "fallback", "optional"],
  fontFamily: [
    "<family-name>",
    "serif",
    "sans-serif",
    "cursive",
    "fantasy",
    "monospace",
    "system-ui",
    "ui-serif",
    "ui-sans-serif",
    "ui-monospace",
    "ui-rounded",
    "emoji",
    "math",
    "fangsong",
    "inherit",
  ],
  fontFeatureSettings: ["normal", "<string>", "<number>"],
  fontKerning: ["auto", "normal", "none"],
  fontOpticalSizing: ["auto", "none"],
  fontPalette: ["auto", "none", "<string>"],
  fontSize: [
    "<absolute-size>",
    "<relative-size>",
    "<length>",
    "<percentage>",
    "small",
    "large",
  ],
  fontStretch: [
    "normal",
    "ultra-condensed",
    "extra-condensed",
    "condensed",
    "semi-condensed",
    "semi-expanded",
    "expanded",
    "extra-expanded",
    "ultra-expanded",
  ],
  fontStyle: ["normal", "italic", "oblique"],
  fontSynthesis: ["none", "weight", "style", "weight style"],
  fontSynthesisSmallCaps: ["auto", "none"],
  fontSynthesisStyle: ["auto", "none"],
  fontSynthesisWeight: ["auto", "none"],
  fontVariant: [
    "normal",
    "small-caps",
    "all-small-caps",
    "petite-caps",
    "all-petite-caps",
    "unicase",
    "titling-caps",
  ],
  fontVariantAlternates: [
    "normal",
    "historical-forms",
    "styleset",
    "character-variant",
    "swash",
    "ornaments",
    "annotation",
    "ruby",
  ],
  fontVariantCaps: [
    "normal",
    "small-caps",
    "all-small-caps",
    "petite-caps",
    "all-petite-caps",
    "unicase",
    "titling-caps",
  ],
  fontVariantEastAsian: [
    "normal",
    "jis78",
    "jis83",
    "jis90",
    "jis04",
    "simplified",
    "traditional",
  ],
  fontVariantLigatures: [
    "normal",
    "none",
    "common-ligatures",
    "no-common-ligatures",
    "discretionary-ligatures",
    "no-discretionary-ligatures",
    "historical-ligatures",
    "no-historical-ligatures",
    "contextual",
    "no-contextual",
  ],
  fontVariantNumeric: [
    "normal",
    "ordinal",
    "slashed-zero",
    "lining-nums",
    "oldstyle-nums",
    "proportional-nums",
    "tabular-nums",
    "diagonal-fractions",
    "stacked-fractions",
  ],
  fontVariantPosition: ["normal", "sub", "super"],
  fontVariationSettings: ["normal", "<font-variation-settings>", "inherit"],
  fontWeight: ["normal", "bold", "bolder", "lighter", "<number>", "inherit"],
  forcedColorAdjust: ["auto", "none"],
  gap: ["<length-percentage>"],
  grid: ["none", "<grid-template>", "<grid-gap>"],
  gridArea: ["<custom-ident>", "auto"],
  gridAutoColumns: ["auto", "<length-percentage>"],
  gridAutoFlow: ["row", "column", "dense", "row dense", "column dense"],
  gridAutoRows: ["auto", "<length-percentage>"],
  gridColumn: ["<grid-line>", "span <integer>", "span <custom-ident>", "auto"],
  gridColumnEnd: [
    "<grid-line>",
    "span <integer>",
    "span <custom-ident>",
    "auto",
  ],
  gridColumnGap: ["<length-percentage>"],
  gridColumnStart: [
    "<grid-line>",
    "span <integer>",
    "span <custom-ident>",
    "auto",
  ],
  gridGap: ["<grid-gap>"],
  gridRow: ["<grid-line>", "span <integer>", "span <custom-ident>", "auto"],
  gridRowEnd: ["<grid-line>", "span <integer>", "span <custom-ident>", "auto"],
  gridRowGap: ["<length-percentage>"],
  gridRowStart: [
    "<grid-line>",
    "span <integer>",
    "span <custom-ident>",
    "auto",
  ],
  gridTemplate: [
    "none",
    "subgrid",
    "<grid-template-rows> / <grid-template-columns>",
    "<custom-ident>",
  ],
  gridTemplateAreas: ["none", "<string>"],
  gridTemplateColumns: ["none", "subgrid", "<track-list>"],
  gridTemplateRows: ["none", "subgrid", "<track-list>"],
  height: [
    "<length-percentage>",
    "auto",
    "fill-available",
    "fit-content",
    "max-content",
    "min-content",
  ],
  hyphenateCharacter: ["auto", "<string>"],
  hyphenateLimitChars: ["auto", "no-limit", "<integer>"],
  hyphens: ["manual", "none", "auto"],
  imageOrientation: ["auto", "from-image", "<angle>"],
  imageRendering: ["auto", "crisp-edges", "pixelated"],
  inherits: ["<custom-ident>", "inherit", "initial", "unset"],
  initialLetter: ["normal", "initial", "unset", "<number>"],
  initialValue: ["inherit", "initial", "unset"],
  inlineSize: [
    "<length-percentage>",
    "auto",
    "min-content",
    "max-content",
    "fit-content",
    "fill-available",
  ],
  inset: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  insetBlock: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  insetBlockEnd: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  insetBlockStart: [
    "<length-percentage>",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  insetInline: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  insetInlineEnd: [
    "<length-percentage>",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  insetInlineStart: [
    "<length-percentage>",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  isolation: ["auto", "isolate"],
  justifyContent: [
    "flex-start",
    "flex-end",
    "center",
    "space-between",
    "space-around",
    "space-evenly",
    "start",
    "end",
    "left",
    "right",
  ],
  justifyItems: [
    "auto",
    "normal",
    "stretch",
    "center",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "self-start",
    "self-end",
    "left",
    "right",
    "baseline",
    "first baseline",
    "last baseline",
  ],
  justifySelf: [
    "auto",
    "normal",
    "stretch",
    "center",
    "start",
    "end",
    "self-start",
    "self-end",
    "left",
    "right",
    "baseline",
    "first baseline",
    "last baseline",
  ],
  left: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  letterSpacing: ["normal", "<length>"],
  lightingColor: ["<color>", "inherit", "initial", "unset"],
  lineBreak: ["auto", "loose", "normal", "strict", "anywhere"],
  lineGapOverride: ["normal", "none"],
  lineHeight: [
    "normal",
    "<number>",
    "<length>",
    "<percentage>",
    "inherit",
    "initial",
    "unset",
  ],
  listStyle: [
    "<list-style-type>",
    "<list-style-position>",
    "<list-style-image>",
  ],
  listStyleImage: ["none", "<image>", "inherit", "initial", "unset"],
  listStylePosition: ["inside", "outside", "inherit", "initial", "unset"],
  listStyleType: [
    "none",
    "disc",
    "circle",
    "square",
    "decimal",
    "decimal-leading-zero",
    "lower-roman",
    "upper-roman",
    "lower-greek",
    "lower-alpha",
    "lower-latin",
    "upper-alpha",
    "upper-latin",
    "arabic-indic",
    "armenian",
    "bengali",
    "cambodian",
    "cjk-earthly-branch",
    "cjk-heavenly-stem",
    "cjk-ideographic",
    "devanagari",
    "ethiopic-numeric",
    "georgian",
    "gujarati",
    "gurmukhi",
    "hebrew",
    "hiragana",
    "hiragana-iroha",
    "japanese-formal",
    "japanese-informal",
    "kannada",
    "katakana",
    "katakana-iroha",
    "khmer",
    "korean-hangul-formal",
    "korean-hanja-formal",
    "korean-hanja-informal",
    "lao",
    "lower-alpha",
    "lower-armenian",
    "lower-greek",
    "lower-latin",
    "lower-norwegian",
    "lower-roman",
    "malayalam",
    "mongolian",
    "myanmar",
    "oriya",
    "persian",
    "simp-chinese-formal",
    "simp-chinese-informal",
    "tamil",
    "telugu",
    "thai",
    "tibetan",
    "trad-chinese-formal",
    "trad-chinese-informal",
    "upper-alpha",
    "upper-armenian",
    "upper-greek",
    "upper-latin",
    "upper-norwegian",
    "upper-roman",
    "disclosure-open",
    "disclosure-closed",
  ],
  margin: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  marginBlock: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  marginBlockEnd: [
    "<length-percentage>",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  marginBlockStart: [
    "<length-percentage>",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  marginBottom: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  marginInline: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  marginInlineEnd: [
    "<length-percentage>",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  marginInlineStart: [
    "<length-percentage>",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  marginLeft: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  marginRight: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  marginTop: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  marker: ["<url>", "none", "inherit", "initial", "unset"],
  markerEnd: ["<url>", "none", "inherit", "initial", "unset"],
  markerMid: ["<url>", "none", "inherit", "initial", "unset"],
  markerStart: ["<url>", "none", "inherit", "initial", "unset"],
  mask: ["<mask-reference>", "none"],
  maskClip: [
    "border-box",
    "content-box",
    "padding-box",
    "inherit",
    "initial",
    "unset",
  ],
  maskComposite: [
    "add",
    "exclude",
    "intersect",
    "subtract",
    "inherit",
    "initial",
    "unset",
  ],
  maskImage: ["none", "<image>", "inherit", "initial", "unset"],
  maskMode: ["alpha", "luminance", "inherit", "initial", "unset"],
  maskOrigin: [
    "border-box",
    "content-box",
    "padding-box",
    "inherit",
    "initial",
    "unset",
  ],
  maskPosition: ["<position>", "inherit", "initial", "unset"],
  maskRepeat: [
    "repeat",
    "no-repeat",
    "repeat-x",
    "repeat-y",
    "inherit",
    "initial",
    "unset",
  ],
  maskSize: [
    "<length-percentage>",
    "auto",
    "cover",
    "contain",
    "inherit",
    "initial",
    "unset",
  ],
  maskType: ["alpha", "luminance", "auto", "inherit", "initial", "unset"],
  mathDepth: ["auto", "0", "inherit", "initial", "unset"],
  mathShift: ["auto", "0", "inherit", "initial", "unset"],
  mathStyle: [
    "normal",
    "italic",
    "script",
    "script-script",
    "script-script",
    "double-struck",
    "fraktur",
    "sans-serif",
    "sans-serif-italic",
    "sans-serif-bold",
    "sans-serif-bold-italic",
    "inherit",
    "initial",
    "unset",
  ],
  maxBlockSize: [
    "<length-percentage>",
    "none",
    "max-content",
    "min-content",
    "fit-content",
    "fill-available",
    "inherit",
    "initial",
    "unset",
  ],
  maxHeight: [
    "<length-percentage>",
    "none",
    "max-content",
    "min-content",
    "fit-content",
    "fill-available",
    "inherit",
    "initial",
    "unset",
  ],
  maxInlineSize: [
    "<length-percentage>",
    "none",
    "max-content",
    "min-content",
    "fit-content",
    "fill-available",
    "inherit",
    "initial",
    "unset",
  ],
  maxWidth: [
    "<length-percentage>",
    "none",
    "max-content",
    "min-content",
    "fit-content",
    "fill-available",
    "inherit",
    "initial",
    "unset",
  ],
  minBlockSize: [
    "<length-percentage>",
    "auto",
    "min-content",
    "max-content",
    "fit-content",
    "fill-available",
    "inherit",
    "initial",
    "unset",
  ],
  minHeight: [
    "<length-percentage>",
    "auto",
    "min-content",
    "max-content",
    "fit-content",
    "fill-available",
    "inherit",
    "initial",
    "unset",
  ],
  minInlineSize: [
    "<length-percentage>",
    "auto",
    "min-content",
    "max-content",
    "fit-content",
    "fill-available",
    "inherit",
    "initial",
    "unset",
  ],
  minWidth: [
    "<length-percentage>",
    "auto",
    "min-content",
    "max-content",
    "fit-content",
    "fill-available",
    "inherit",
    "initial",
    "unset",
  ],
  mixBlendMode: [
    "normal",
    "multiply",
    "screen",
    "overlay",
    "darken",
    "lighten",
    "color-dodge",
    "color-burn",
    "hard-light",
    "soft-light",
    "difference",
    "exclusion",
    "hue",
    "saturation",
    "color",
    "luminosity",
    "inherit",
    "initial",
    "unset",
  ],
  negative: ["normal", "none", "inherit", "initial", "unset"],
  objectFit: [
    "fill",
    "contain",
    "cover",
    "none",
    "scale-down",
    "inherit",
    "initial",
    "unset",
  ],
  objectPosition: ["<position>", "inherit", "initial", "unset"],
  objectViewBox: ["<svg-view-box>", "inherit", "initial", "unset"],
  offset: ["auto", "<position>", "inherit", "initial", "unset"],
  offsetAnchor: ["auto", "<position>", "inherit", "initial", "unset"],
  offsetDistance: [
    "auto",
    "<length-percentage>",
    "inherit",
    "initial",
    "unset",
  ],
  offsetPath: ["none", "<path>", "inherit", "initial", "unset"],
  offsetPosition: ["auto", "<position>", "inherit", "initial", "unset"],
  offsetRotate: ["auto", "<angle>", "inherit", "initial", "unset"],
  opacity: ["<alpha-value>", "inherit", "initial", "unset"],
  order: ["<integer>", "inherit", "initial", "unset"],
  orphans: ["<integer>", "inherit", "initial", "unset"],
  outline: [
    "<outline-color> || <outline-style> || <outline-width>",
    "invert",
    "inherit",
    "initial",
    "unset",
  ],
  outlineColor: ["<color> | invert | inherit | initial | unset"],
  outlineOffset: ["<length>", "inherit", "initial", "unset"],
  outlineStyle: [
    "auto",
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
    "inherit",
    "initial",
    "unset",
  ],
  outlineWidth: ["<line-width>", "inherit", "initial", "unset"],
  overflow: [
    "visible",
    "hidden",
    "scroll",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  overflowAnchor: ["auto", "none", "inherit", "initial", "unset"],
  overflowClipMargin: ["auto", "none", "inherit", "initial", "unset"],
  overflowWrap: [
    "normal",
    "break-word",
    "anywhere",
    "inherit",
    "initial",
    "unset",
  ],
  overflowX: [
    "visible",
    "hidden",
    "scroll",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  overflowY: [
    "visible",
    "hidden",
    "scroll",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  overlay: ["<position>", "inherit", "initial", "unset"],
  overrideColors: ["currentcolor", "inherit", "initial", "unset"],
  overscrollBehavior: [
    "auto",
    "contain",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  overscrollBehaviorBlock: [
    "auto",
    "contain",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  overscrollBehaviorInline: [
    "auto",
    "contain",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  overscrollBehaviorX: [
    "auto",
    "contain",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  overscrollBehaviorY: [
    "auto",
    "contain",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  pad: [
    "padding-box",
    "content-box",
    "border-box",
    "inherit",
    "initial",
    "unset",
  ],
  padding: ["<length-percentage>", "inherit", "initial", "unset"],
  paddingBlock: ["<length-percentage>", "inherit", "initial", "unset"],
  paddingBlockEnd: ["<length-percentage>", "inherit", "initial", "unset"],
  paddingBlockStart: ["<length-percentage>", "inherit", "initial", "unset"],
  paddingBottom: ["<length-percentage>", "inherit", "initial", "unset"],
  paddingInline: ["<length-percentage>", "inherit", "initial", "unset"],
  paddingInlineEnd: ["<length-percentage>", "inherit", "initial", "unset"],
  paddingInlineStart: ["<length-percentage>", "inherit", "initial", "unset"],
  paddingLeft: ["<length-percentage>", "inherit", "initial", "unset"],
  paddingRight: ["<length-percentage>", "inherit", "initial", "unset"],
  paddingTop: ["<length-percentage>", "inherit", "initial", "unset"],
  page: ["<string> | <uri> | auto", "inherit", "initial", "unset"],
  pageBreakAfter: [
    "auto",
    "always",
    "avoid",
    "left",
    "right",
    "inherit",
    "initial",
    "unset",
  ],
  pageBreakBefore: [
    "auto",
    "always",
    "avoid",
    "left",
    "right",
    "inherit",
    "initial",
    "unset",
  ],
  pageBreakInside: ["auto", "avoid", "inherit", "initial", "unset"],
  pageOrientation: [
    "auto",
    "portrait",
    "landscape",
    "inherit",
    "initial",
    "unset",
  ],
  paintOrder: [
    "normal",
    "fill",
    "stroke",
    "markers",
    "inherit",
    "initial",
    "unset",
  ],
  perspective: ["none", "<length>", "inherit", "initial", "unset"],
  perspectiveOrigin: ["<position>", "inherit", "initial", "unset"],
  placeContent: [
    "normal",
    "<content-distribution> <content-position>",
    "inherit",
    "initial",
    "unset",
  ],
  placeItems: [
    "auto",
    "normal",
    "stretch",
    "center",
    "<baseline-position>",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "self-start",
    "self-end",
    "left",
    "right",
    "safe center",
    "unsafe center",
    "<content-distribution> <content-position>",
    "inherit",
    "initial",
    "unset",
  ],
  placeSelf: [
    "auto",
    "normal",
    "stretch",
    "center",
    "<baseline-position>",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "self-start",
    "self-end",
    "left",
    "right",
    "safe center",
    "unsafe center",
    "<content-distribution> <content-position>",
    "inherit",
    "initial",
    "unset",
  ],
  pointerEvents: [
    "auto",
    "none",
    "visiblePainted",
    "visibleFill",
    "visibleStroke",
    "visible",
    "painted",
    "fill",
    "stroke",
    "all",
    "inherit",
    "initial",
    "unset",
  ],
  position: [
    "static",
    "relative",
    "absolute",
    "fixed",
    "sticky",
    "inherit",
    "initial",
    "unset",
  ],
  prefix: ["<string>", "inherit", "initial", "unset"],
  quotes: ["<string> <string>", "none", "inherit", "initial", "unset"],
  r: ["<length>", "inherit", "initial", "unset"],
  range: ["none", "<range-token>", "inherit", "initial", "unset"],
  resize: [
    "none",
    "both",
    "horizontal",
    "vertical",
    "inherit",
    "initial",
    "unset",
  ],
  right: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  rotate: ["<angle>", "none", "inherit", "initial", "unset"],
  rowGap: ["<length>", "normal", "inherit", "initial", "unset"],
  rubyPosition: [
    "over",
    "under",
    "inter-character",
    "inherit",
    "initial",
    "unset",
  ],
  rx: ["<length>", "auto", "inherit", "initial", "unset"],
  ry: ["<length>", "auto", "inherit", "initial", "unset"],
  scale: ["none", "scale(<number>, <number>)", "inherit", "initial", "unset"],
  scrollBehavior: ["auto", "smooth", "inherit", "initial", "unset"],
  scrollMargin: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollMarginBlock: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollMarginBlockEnd: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollMarginBlockStart: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollMarginBottom: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollMarginInline: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollMarginInlineEnd: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollMarginInlineStart: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollMarginLeft: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollMarginRight: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollMarginTop: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPadding: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPaddingBlock: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPaddingBlockEnd: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPaddingBlockStart: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPaddingBottom: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPaddingInline: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPaddingInlineEnd: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPaddingInlineStart: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPaddingLeft: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPaddingRight: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollPaddingTop: ["<length>", "auto", "inherit", "initial", "unset"],
  scrollSnapAlign: [
    "none",
    "<string>",
    "<percentage>",
    "start",
    "end",
    "center",
    "inherit",
    "initial",
    "unset",
  ],
  scrollSnapStop: ["normal", "always", "inherit", "initial", "unset"],
  scrollSnapType: [
    "none",
    "mandatory",
    "proximity",
    "inherit",
    "initial",
    "unset",
  ],
  scrollTimeline: ["auto", "none", "<ident>", "inherit", "initial", "unset"],
  scrollTimelineAxis: ["block", "inline", "inherit", "initial", "unset"],
  scrollTimelineName: ["none", "<string>", "inherit", "initial", "unset"],
  scrollbarColor: [
    "auto",
    "dark",
    "light",
    "<color>",
    "inherit",
    "initial",
    "unset",
  ],
  scrollbarGutter: ["auto", "stable", "always", "inherit", "initial", "unset"],
  scrollbarWidth: ["auto", "thin", "none", "inherit", "initial", "unset"],
  shapeImageThreshold: ["<number>", "inherit", "initial", "unset"],
  shapeMargin: ["<length>", "inherit", "initial", "unset"],
  shapeOutside: [
    "none",
    "<shape-box>",
    "<image>",
    "inherit",
    "initial",
    "unset",
  ],
  shapeRendering: [
    "auto",
    "optimizeSpeed",
    "crispEdges",
    "geometricPrecision",
    "inherit",
    "initial",
    "unset",
  ],
  size: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  sizeAdjust: ["none", "<number>", "inherit", "initial", "unset"],
  speak: ["auto", "none", "normal", "spell-out", "inherit", "initial", "unset"],
  speakAs: [
    "normal",
    "spell-out",
    "digits",
    "literal-punctuation",
    "no-punctuation",
    "inherit",
    "initial",
    "unset",
  ],
  src: ["<image> | <string>", "inherit", "initial", "unset"],
  stopColor: ["<color>", "inherit", "initial", "unset"],
  stopOpacity: ["<number>", "inherit", "initial", "unset"],
  stroke: ["<paint>", "inherit", "initial", "unset"],
  strokeDasharray: [
    "<length>",
    "<percentage>",
    "<number>",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  strokeDashoffset: ["<length>", "<percentage>", "inherit", "initial", "unset"],
  strokeLinecap: ["butt", "round", "square", "inherit", "initial", "unset"],
  strokeLinejoin: ["miter", "round", "bevel", "inherit", "initial", "unset"],
  strokeMiterlimit: ["<number>", "inherit", "initial", "unset"],
  strokeOpacity: ["<number>", "inherit", "initial", "unset"],
  strokeWidth: ["<length>", "inherit", "initial", "unset"],
  suffix: ["<string>", "inherit", "initial", "unset"],
  symbols: ["<string>", "inherit", "initial", "unset"],
  syntax: ["normal", "none", "<string>", "inherit", "initial", "unset"],
  system: [
    "<string>",
    "fixed",
    "surrounding",
    "ignore",
    "extend",
    "none",
    "manual",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  tabSize: ["<length>", "<number>", "inherit", "initial", "unset"],
  tableLayout: ["auto", "fixed", "inherit", "initial", "unset"],
  textAlign: [
    "start",
    "end",
    "left",
    "right",
    "center",
    "justify",
    "match-parent",
    "inherit",
    "initial",
    "unset",
  ],
  textAlignLast: [
    "auto",
    "start",
    "end",
    "left",
    "right",
    "center",
    "justify",
    "inherit",
    "initial",
    "unset",
  ],
  textAnchor: ["start", "middle", "end", "inherit", "initial", "unset"],
  textCombineUpright: ["none", "all", "digits", "inherit", "initial", "unset"],
  textDecoration: [
    "none",
    "underline",
    "overline",
    "line-through",
    "blink",
    "inherit",
    "initial",
    "unset",
  ],
  textDecorationColor: ["<color>", "inherit", "initial", "unset"],
  textDecorationLine: [
    "none",
    "underline",
    "overline",
    "line-through",
    "inherit",
    "initial",
    "unset",
  ],
  textDecorationSkipInk: [
    "auto",
    "none",
    "all",
    "box-decoration",
    "text-decoration",
    "inherit",
    "initial",
    "unset",
  ],
  textDecorationStyle: [
    "solid",
    "double",
    "dotted",
    "dashed",
    "wavy",
    "inherit",
    "initial",
    "unset",
  ],
  textDecorationThickness: [
    "auto",
    "from-font",
    "<length>",
    "inherit",
    "initial",
    "unset",
  ],
  textEmphasis: ["<string>", "<image>", "none", "inherit", "initial", "unset"],
  textEmphasisColor: ["<color>", "inherit", "initial", "unset"],
  textEmphasisPosition: [
    "over",
    "under",
    "left",
    "right",
    "inherit",
    "initial",
    "unset",
  ],
  textEmphasisStyle: [
    "none",
    "filled",
    "open",
    "dot",
    "circle",
    "double-circle",
    "triangle",
    "sesame",
    "inherit",
    "initial",
    "unset",
  ],
  textIndent: ["<length>", "<percentage>", "inherit", "initial", "unset"],
  textOrientation: [
    "mixed",
    "upright",
    "sideways",
    "inherit",
    "initial",
    "unset",
  ],
  textOverflow: ["clip", "ellipsis", "inherit", "initial", "unset"],
  textRendering: [
    "auto",
    "optimizeSpeed",
    "optimizeLegibility",
    "geometricPrecision",
    "inherit",
    "initial",
    "unset",
  ],
  textShadow: [
    "<color>{2,} <length>{0,2}",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  textSizeAdjust: ["none", "<percentage>", "inherit", "initial", "unset"],
  textTransform: [
    "capitalize",
    "uppercase",
    "lowercase",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  textUnderlineOffset: ["auto", "<length>", "inherit", "initial", "unset"],
  textUnderlinePosition: [
    "auto",
    "under",
    "left",
    "right",
    "inherit",
    "initial",
    "unset",
  ],
  textWrap: ["normal", "none", "unrestricted", "inherit", "initial", "unset"],
  timelineScope: ["<ident>", "auto", "grow", "inherit", "initial", "unset"],
  top: ["<length-percentage>", "auto", "inherit", "initial", "unset"],
  touchAction: [
    "auto",
    "none",
    "pan-x",
    "pan-y",
    "manipulation",
    "inherit",
    "initial",
    "unset",
  ],
  transform: ["none", "<transform-function>", "inherit", "initial", "unset"],
  transformBox: [
    "border-box",
    "fill-box",
    "view-box",
    "inherit",
    "initial",
    "unset",
  ],
  transformOrigin: [
    "<percentage>",
    "<length>",
    "left",
    "center",
    "right",
    "top",
    "bottom",
    "inherit",
    "initial",
    "unset",
  ],
  transformStyle: ["flat", "preserve-3d", "inherit", "initial", "unset"],
  transition: ["<single-transition>#", "none", "inherit", "initial", "unset"],
  transitionBehavior: [
    "auto",
    "auto none",
    "instantly",
    "smoothly",
    "inherit",
    "initial",
    "unset",
  ],
  transitionDelay: ["<time>", "inherit", "initial", "unset"],
  transitionDuration: ["<time>", "inherit", "initial", "unset"],
  transitionProperty: ["none", "all", "inherit", "initial", "unset"],
  transitionTimingFunction: [
    "ease",
    "linear",
    "ease-in",
    "ease-out",
    "ease-in-out",
    "step-start",
    "step-end",
    "steps",
    "cubic-bezier",
    "inherit",
    "initial",
    "unset",
  ],
  translate: [
    "none",
    "translate(<length-percentage>, <length-percentage>)",
    "inherit",
    "initial",
    "unset",
  ],
  unicodeBidi: [
    "normal",
    "embed",
    "isolate",
    "bidi-override",
    "isolate-override",
    "plaintext",
    "inherit",
    "initial",
    "unset",
  ],
  unicodeRange: ["<urange>", "inherit", "initial", "unset"],
  userSelect: [
    "auto",
    "none",
    "text",
    "contain",
    "all",
    "inherit",
    "initial",
    "unset",
  ],
  vectorEffect: ["none", "non-scaling-stroke", "inherit", "initial", "unset"],
  verticalAlign: [
    "baseline",
    "sub",
    "super",
    "top",
    "text-top",
    "middle",
    "bottom",
    "text-bottom",
    "<percentage>",
    "<length>",
    "inherit",
    "initial",
    "unset",
  ],
  viewTimeline: ["none", "<time>", "inherit", "initial", "unset"],
  viewTimelineAxis: ["x", "y", "z", "none", "inherit", "initial", "unset"],
  viewTimelineInset: ["<length>", "auto", "inherit", "initial", "unset"],
  viewTimelineName: ["<string>", "none", "inherit", "initial", "unset"],
  viewTransitionName: ["<string>", "none", "inherit", "initial", "unset"],
  visibility: ["visible", "hidden", "collapse", "inherit", "initial", "unset"],
  webkitAlignContent: [
    "normal",
    "baseline",
    "center",
    "space-around",
    "space-between",
    "space-evenly",
    "stretch",
    "inherit",
    "initial",
    "unset",
  ],
  webkitAlignItems: [
    "normal",
    "baseline",
    "center",
    "stretch",
    "inherit",
    "initial",
    "unset",
  ],
  webkitAlignSelf: [
    "auto",
    "normal",
    "baseline",
    "center",
    "stretch",
    "inherit",
    "initial",
    "unset",
  ],
  webkitAnimation: [
    "<single-animation>#",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  webkitAnimationDelay: ["<time>", "inherit", "initial", "unset"],
  webkitAnimationDirection: [
    "normal",
    "reverse",
    "alternate",
    "alternate-reverse",
    "inherit",
    "initial",
    "unset",
  ],
  webkitAnimationDuration: ["<time>", "inherit", "initial", "unset"],
  webkitAnimationFillMode: [
    "none",
    "forwards",
    "backwards",
    "both",
    "inherit",
    "initial",
    "unset",
  ],
  webkitAnimationIterationCount: [
    "<number>",
    "infinite",
    "inherit",
    "initial",
    "unset",
  ],
  webkitAnimationName: ["<ident>", "none", "inherit", "initial", "unset"],
  webkitAnimationPlayState: [
    "running",
    "paused",
    "inherit",
    "initial",
    "unset",
  ],
  webkitAnimationTimingFunction: [
    "ease",
    "linear",
    "ease-in",
    "ease-out",
    "ease-in-out",
    "step-start",
    "step-end",
    "steps",
    "cubic-bezier",
    "inherit",
    "initial",
    "unset",
  ],
  webkitAppRegion: ["no-drag", "drag", "inherit", "initial", "unset"],
  webkitAppearance: [
    "none",
    "button",
    "button-bevel",
    "caps-lock-indicator",
    "caret",
    "checkbox",
    "default-button",
    "listbox",
    "listitem",
    "media-fullscreen-button",
    "media-mute-button",
    "media-play-button",
    "media-seek-back-button",
    "media-seek-forward-button",
    "media-slider",
    "media-sliderthumb",
    "menulist",
    "menulist-button",
    "menulist-text",
    "menulist-textfield",
    "meter",
    "none",
    "progress-bar",
    "progress-bar-value",
    "push-button",
    "radio",
    "searchfield",
    "searchfield-cancel-button",
    "searchfield-decoration",
    "searchfield-results-button",
    "searchfield-results-decoration",
    "slider-horizontal",
    "slider-vertical",
    "square-button",
    "textarea",
    "textfield",
    "volume-slider-horizontal",
    "volume-slider-vertical",
    "window",
    "inherit",
    "initial",
    "unset",
  ],
  webkitBackfaceVisibility: [
    "visible",
    "hidden",
    "inherit",
    "initial",
    "unset",
  ],
  webkitBackgroundClip: [
    "border-box",
    "padding-box",
    "content-box",
    "text",
    "inherit",
    "initial",
    "unset",
  ],
  webkitBackgroundOrigin: [
    "padding-box",
    "border-box",
    "content-box",
    "inherit",
    "initial",
    "unset",
  ],
  webkitBackgroundSize: [
    "<bg-size>",
    "auto",
    "cover",
    "contain",
    "inherit",
    "initial",
    "unset",
  ],
  webkitBorderAfter: ["<border-width>", "inherit", "initial", "unset"],
  webkitBorderAfterColor: ["<color>", "inherit", "initial", "unset"],
  webkitBorderAfterStyle: ["<border-style>", "inherit", "initial", "unset"],
  webkitBorderAfterWidth: ["<border-width>", "inherit", "initial", "unset"],
  webkitBorderBefore: ["<border-width>", "inherit", "initial", "unset"],
  webkitBorderBeforeColor: ["<color>", "inherit", "initial", "unset"],
  webkitBorderBeforeStyle: ["<border-style>", "inherit", "initial", "unset"],
  webkitBorderBeforeWidth: ["<border-width>", "inherit", "initial", "unset"],
  webkitBorderBottomLeftRadius: ["<length>", "inherit", "initial", "unset"],
  webkitBorderBottomRightRadius: ["<length>", "inherit", "initial", "unset"],
  webkitBorderEnd: ["<border-width>", "inherit", "initial", "unset"],
  webkitBorderEndColor: ["<color>", "inherit", "initial", "unset"],
  webkitBorderEndStyle: ["<border-style>", "inherit", "initial", "unset"],
  webkitBorderEndWidth: ["<border-width>", "inherit", "initial", "unset"],
  webkitBorderHorizontalSpacing: ["<length>", "inherit", "initial", "unset"],
  webkitBorderImage: [
    "<border-image-source>",
    "<border-image-slice>",
    "<border-image-width>",
    "<border-image-outset>",
    "<border-image-repeat>",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  webkitBorderRadius: ["<length>", "inherit", "initial", "unset"],
  webkitBorderStart: ["<border-width>", "inherit", "initial", "unset"],
  webkitBorderStartColor: ["<color>", "inherit", "initial", "unset"],
  webkitBorderStartStyle: ["<border-style>", "inherit", "initial", "unset"],
  webkitBorderStartWidth: ["<border-width>", "inherit", "initial", "unset"],
  webkitBorderTopLeftRadius: ["<length>", "inherit", "initial", "unset"],
  webkitBorderTopRightRadius: ["<length>", "inherit", "initial", "unset"],
  webkitBorderVerticalSpacing: ["<length>", "inherit", "initial", "unset"],
  webkitBoxAlign: [
    "stretch",
    "start",
    "center",
    "end",
    "baseline",
    "inherit",
    "initial",
    "unset",
  ],
  webkitBoxDecorationBreak: ["slice", "clone", "inherit", "initial", "unset"],
  webkitBoxDirection: ["normal", "reverse", "inherit", "initial", "unset"],
  webkitBoxFlex: ["<number>", "inherit", "initial", "unset"],
  webkitBoxOrdinalGroup: ["<integer>", "inherit", "initial", "unset"],
  webkitBoxOrient: ["horizontal", "vertical", "inherit", "initial", "unset"],
  webkitBoxPack: [
    "start",
    "center",
    "end",
    "justify",
    "inherit",
    "initial",
    "unset",
  ],
  webkitBoxReflect: [
    "none",
    "<length-percentage>",
    "<string>",
    "inherit",
    "initial",
    "unset",
  ],
  webkitBoxShadow: ["<shadow>#", "none", "inherit", "initial", "unset"],
  webkitBoxSizing: ["content-box", "border-box", "inherit", "initial", "unset"],
  webkitClipPath: ["none", "<url>", "<shape>", "inherit", "initial", "unset"],
  webkitColumnBreakAfter: [
    "auto",
    "always",
    "avoid",
    "left",
    "right",
    "inherit",
    "initial",
    "unset",
  ],
  webkitColumnBreakBefore: [
    "auto",
    "always",
    "avoid",
    "left",
    "right",
    "inherit",
    "initial",
    "unset",
  ],
  webkitColumnBreakInside: ["auto", "avoid", "inherit", "initial", "unset"],
  webkitColumnCount: ["<integer>", "auto", "inherit", "initial", "unset"],
  webkitColumnGap: ["<length>", "normal", "inherit", "initial", "unset"],
  webkitColumnRule: [
    "<border-width> || <border-style> || <color>",
    "inherit",
    "initial",
    "unset",
  ],
  webkitColumnRuleColor: ["<color>", "inherit", "initial", "unset"],
  webkitColumnRuleStyle: ["<border-style>", "inherit", "initial", "unset"],
  webkitColumnRuleWidth: ["<border-width>", "inherit", "initial", "unset"],
  webkitColumnSpan: ["none", "all", "inherit", "initial", "unset"],
  webkitColumnWidth: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitColumns: ["<length> <color>?", "auto", "inherit", "initial", "unset"],
  webkitFilter: ["<filter-function>#", "none", "inherit", "initial", "unset"],
  webkitFlex: [
    "none",
    "auto",
    "<flex-grow> <flex-shrink>? <flex-basis>?",
    "inherit",
    "initial",
    "unset",
  ],
  webkitFlexBasis: ["<width>", "auto", "inherit", "initial", "unset"],
  webkitFlexDirection: [
    "row",
    "row-reverse",
    "column",
    "column-reverse",
    "inherit",
    "initial",
    "unset",
  ],
  webkitFlexFlow: [
    "<flex-direction> || <flex-wrap>",
    "inherit",
    "initial",
    "unset",
  ],
  webkitFlexGrow: ["<number>", "inherit", "initial", "unset"],
  webkitFlexShrink: ["<number>", "inherit", "initial", "unset"],
  webkitFlexWrap: [
    "nowrap",
    "wrap",
    "wrap-reverse",
    "inherit",
    "initial",
    "unset",
  ],
  webkitFontFeatureSettings: ["normal", "inherit", "initial", "unset"],
  webkitFontSmoothing: [
    "auto",
    "antialiased",
    "subpixel-antialiased",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  webkitHyphenateCharacter: ["auto", "none", "inherit", "initial", "unset"],
  webkitJustifyContent: [
    "flex-start",
    "flex-end",
    "center",
    "space-between",
    "space-around",
    "inherit",
    "initial",
    "unset",
  ],
  webkitLineBreak: [
    "auto",
    "loose",
    "normal",
    "strict",
    "inherit",
    "initial",
    "unset",
  ],
  webkitLineClamp: ["<integer>", "none", "inherit", "initial", "unset"],
  webkitLocale: ["<string>", "inherit", "initial", "unset"],
  webkitLogicalHeight: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitLogicalWidth: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitMarginAfter: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitMarginBefore: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitMarginEnd: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitMarginStart: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitMask: ["<mask-reference>", "none", "inherit", "initial", "unset"],
  webkitMaskBoxImage: [
    "<mask-box-image-source>",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskBoxImageOutset: [
    "<mask-box-image-slice>",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskBoxImageRepeat: [
    "<mask-box-image-repeat>",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskBoxImageSlice: [
    "<mask-box-image-slice>",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskBoxImageSource: ["<image>", "none", "inherit", "initial", "unset"],
  webkitMaskBoxImageWidth: [
    "<mask-box-image-width>",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskClip: [
    "<mask-reference>",
    "border-box",
    "padding-box",
    "content-box",
    "text",
    "no-clip",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskComposite: [
    "clear",
    "copy",
    "source-over",
    "source-in",
    "source-out",
    "source-atop",
    "destination-over",
    "destination-in",
    "destination-out",
    "destination-atop",
    "xor",
    "plus",
    "minus",
    "multiply",
    "screen",
    "overlay",
    "darken",
    "lighten",
    "color-dodge",
    "color-burn",
    "hard-light",
    "soft-light",
    "difference",
    "exclusion",
    "hue",
    "saturation",
    "color",
    "luminosity",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskImage: ["<mask-reference>", "none", "inherit", "initial", "unset"],
  webkitMaskOrigin: [
    "<mask-reference>",
    "border-box",
    "padding-box",
    "content-box",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskPosition: ["<position>", "inherit", "initial", "unset"],
  webkitMaskPositionX: [
    "<length>",
    "left",
    "center",
    "right",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskPositionY: [
    "<length>",
    "top",
    "center",
    "bottom",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskRepeat: [
    "repeat-x",
    "repeat-y",
    "repeat",
    "no-repeat",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaskSize: [
    "<length-percentage>",
    "<cover-size>",
    "<contain-size>",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaxLogicalHeight: [
    "<length>",
    "none",
    "max-content",
    "min-content",
    "fit-content",
    "fill-available",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMaxLogicalWidth: [
    "<length>",
    "none",
    "max-content",
    "min-content",
    "fit-content",
    "fill-available",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMinLogicalHeight: [
    "<length>",
    "max-content",
    "min-content",
    "fit-content",
    "fill-available",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  webkitMinLogicalWidth: [
    "<length>",
    "max-content",
    "min-content",
    "fit-content",
    "fill-available",
    "auto",
    "inherit",
    "initial",
    "unset",
  ],
  webkitOpacity: ["<number>", "inherit", "initial", "unset"],
  webkitOrder: ["<integer>", "inherit", "initial", "unset"],
  webkitPaddingAfter: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitPaddingBefore: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitPaddingEnd: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitPaddingStart: ["<length>", "auto", "inherit", "initial", "unset"],
  webkitPerspective: ["<length>", "none", "inherit", "initial", "unset"],
  webkitPerspectiveOrigin: ["<position>", "inherit", "initial", "unset"],
  webkitPerspectiveOriginX: [
    "<length>",
    "left",
    "center",
    "right",
    "inherit",
    "initial",
    "unset",
  ],
  webkitPerspectiveOriginY: [
    "<length>",
    "top",
    "center",
    "bottom",
    "inherit",
    "initial",
    "unset",
  ],
  webkitPrintColorAdjust: ["economy", "exact", "inherit", "initial", "unset"],
  webkitRtlOrdering: ["logical", "visual", "inherit", "initial", "unset"],
  webkitRubyPosition: [
    "before",
    "after",
    "inter-character",
    "inherit",
    "initial",
    "unset",
  ],
  webkitShapeImageThreshold: ["<number>", "inherit", "initial", "unset"],
  webkitShapeMargin: ["<length>", "inherit", "initial", "unset"],
  webkitShapeOutside: ["<shape-box>", "none", "inherit", "initial", "unset"],
  webkitTapHighlightColor: ["<color>", "inherit", "initial", "unset"],
  webkitTextCombine: ["none", "horizontal", "inherit", "initial", "unset"],
  webkitTextDecorationsInEffect: [
    "none",
    "underline",
    "overline",
    "line-through",
    "blink",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTextEmphasis: [
    "<text-emphasis-style>",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTextEmphasisColor: ["<color>", "inherit", "initial", "unset"],
  webkitTextEmphasisPosition: [
    "over",
    "under",
    "left",
    "right",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTextEmphasisStyle: [
    "filled",
    "open",
    "dot",
    "circle",
    "double-circle",
    "triangle",
    "sesame",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTextFillColor: [
    "<color>",
    "currentColor",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTextOrientation: [
    "vertical-right",
    "upright",
    "sideways-right",
    "sideways",
    "sideways-left",
    "vertical-left",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTextSecurity: [
    "none",
    "circle",
    "disc",
    "square",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTextSizeAdjust: ["none", "<percentage>", "inherit", "initial", "unset"],
  webkitTextStroke: ["<length> <color>", "none", "inherit", "initial", "unset"],
  webkitTextStrokeColor: [
    "<color>",
    "currentColor",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTextStrokeWidth: ["<length>", "inherit", "initial", "unset"],
  webkitTransform: ["none", "inherit", "initial", "unset"],
  webkitTransformOrigin: ["<position>", "inherit", "initial", "unset"],
  webkitTransformOriginX: [
    "<length>",
    "left",
    "center",
    "right",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTransformOriginY: [
    "<length>",
    "top",
    "center",
    "bottom",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTransformOriginZ: [
    "<length>",
    "center",
    "length",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTransformStyle: ["flat", "preserve-3d", "inherit", "initial", "unset"],
  webkitTransition: [
    "none",
    "all",
    "<property>#",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTransitionDelay: ["<time>", "inherit", "initial", "unset"],
  webkitTransitionDuration: ["<time>", "inherit", "initial", "unset"],
  webkitTransitionProperty: [
    "none",
    "all",
    "<property>#",
    "inherit",
    "initial",
    "unset",
  ],
  webkitTransitionTimingFunction: [
    "<timing-function>",
    "inherit",
    "initial",
    "unset",
  ],
  webkitUserDrag: ["auto", "none", "element", "inherit", "initial", "unset"],
  webkitUserModify: [
    "read-only",
    "read-write",
    "read-write-plaintext-only",
    "read-write-plaintext",
    "read-write",
    "read-only-plaintext",
    "none",
    "inherit",
    "initial",
    "unset",
  ],
  webkitUserSelect: [
    "none",
    "text",
    "all",
    "auto",
    "contain",
    "inherit",
    "initial",
    "unset",
  ],
  webkitWritingMode: [
    "horizontal-tb",
    "vertical-rl",
    "vertical-lr",
    "sideways-rl",
    "sideways-lr",
    "inherit",
    "initial",
    "unset",
  ],
  whiteSpace: [
    "normal",
    "nowrap",
    "pre",
    "pre-wrap",
    "pre-line",
    "break-spaces",
    "inherit",
    "initial",
    "unset",
  ],
  whiteSpaceCollapse: [
    "collapse",
    "preserve-breaks",
    "inherit",
    "initial",
    "unset",
  ],
  widows: ["<integer>", "inherit", "initial", "unset"],
  width: [
    "<length>",
    "auto",
    "fit-content",
    "min-content",
    "max-content",
    "inherit",
    "initial",
    "unset",
  ],
  willChange: [
    "auto",
    "scroll-position",
    "contents",
    "transform",
    "opacity",
    "left",
    "top",
    "width",
    "height",
    "all",
    "inherit",
    "initial",
    "unset",
  ],
  wordBreak: [
    "normal",
    "break-all",
    "keep-all",
    "break-word",
    "inherit",
    "initial",
    "unset",
  ],
  wordSpacing: ["normal", "<length>", "inherit", "initial", "unset"],
  wordWrap: ["normal", "break-word", "anywhere", "inherit", "initial", "unset"],
  writingMode: [
    "horizontal-tb",
    "vertical-rl",
    "vertical-lr",
    "sideways-rl",
    "sideways-lr",
    "inherit",
    "initial",
    "unset",
  ],
  x: ["<length>", "auto", "inherit", "initial", "unset"],
  y: ["<length>", "auto", "inherit", "initial", "unset"],
  zIndex: ["<integer>", "auto", "inherit", "initial", "unset"],
  zoom: ["normal", "<percentage>", "<number>", "inherit", "initial", "unset"],
  cssText: ["<string>", "inherit", "initial", "unset"],
  length: ["<integer>", "inherit", "initial", "unset"],
  parentRule: ["<css-rule>", "inherit", "initial", "unset"],
  cssFloat: ["left", "right", "none", "inherit", "initial", "unset"],
};

const htmlArray = [
  "a",
  "abbr",
  "address",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "bdi",
  "bdo",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "link",
  "main",
  "map",
  "mark",
  "meta",
  "meter",
  "nav",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "param",
  "picture",
  "pre",
  "progress",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "script",
  "section",
  "select",
  "slot",
  "small",
  "source",
  "span",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "svg",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "u",
  "ul",
  "var",
  "video",
  "wbr",
];

let psuedoClassArray = [
  "hover",
  "active",
  "focus",
  "first-child",
  "last-child",
  "nth-child",
  "checked",
  "disable/enable",
];

export { keyArray, htmlArray, cssValues, psuedoClassArray };
